name: Investigate Push Event Format
on: [push]

jobs:
  print-event:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - run: ls -la /
      - run: echo $GITHUB_EVENT_PATH
      - run: echo $GITHUB_WORKSPACE
      - run: env | sort
